module.exports = {
  apps: [
    {
      name: 'quiz-api',
      cwd: './api',
      script: 'dist/server.js',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      env: {
        NODE_ENV: 'production',
        PORT: '4000',
      },
      env_file: '../.env',
      max_memory_restart: '500M',
      error_file: '/home/ubuntu/.pm2/logs/quiz-api-error.log',
      out_file: '/home/ubuntu/.pm2/logs/quiz-api-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'quiz-player',
      cwd: './apps/player',
      script: 'node_modules/next/dist/bin/next',
      args: 'start --port 4001',
      exec_mode: 'fork',
      instances: 1,
      env: { NODE_ENV: 'production' },
      env_file: './.env',
      max_memory_restart: '300M',
      error_file: '/home/ubuntu/.pm2/logs/quiz-player-error.log',
      out_file: '/home/ubuntu/.pm2/logs/quiz-player-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'quiz-mobile',
      cwd: './apps/mobile',
      script: 'node_modules/next/dist/bin/next',
      args: 'start --port 4002',
      exec_mode: 'fork',
      instances: 1,
      env: { NODE_ENV: 'production' },
      env_file: './.env',
      max_memory_restart: '300M',
      error_file: '/home/ubuntu/.pm2/logs/quiz-mobile-error.log',
      out_file: '/home/ubuntu/.pm2/logs/quiz-mobile-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'quiz-console',
      cwd: './apps/console',
      script: 'node_modules/next/dist/bin/next',
      args: 'start --port 4003',
      exec_mode: 'fork',
      instances: 1,
      env: { NODE_ENV: 'production' },
      env_file: './.env',
      max_memory_restart: '300M',
      error_file: '/home/ubuntu/.pm2/logs/quiz-console-error.log',
      out_file: '/home/ubuntu/.pm2/logs/quiz-console-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'quiz-admin',
      cwd: './apps/admin',
      script: 'node_modules/next/dist/bin/next',
      args: 'start --port 4004',
      exec_mode: 'fork',
      instances: 1,
      env: { NODE_ENV: 'production' },
      env_file: './.env',
      max_memory_restart: '300M',
      error_file: '/home/ubuntu/.pm2/logs/quiz-admin-error.log',
      out_file: '/home/ubuntu/.pm2/logs/quiz-admin-out.log',
      merge_logs: true,
      time: true,
    },
  ],
};
