name: Deploy to VPS

on:
  push:
    branches: [ master ]  # ou master, selon votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/quiz-app
            git pull origin main
            # Ajoutez ici d'autres commandes nécessaires pour votre déploiement
            # Par exemple :
            # npm install
            # npm run build
            # service votre-app restart