name: Deploy to VPS

on:
  push:
    branches: [ master ]  # Branche principale configurée sur master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} '
            cd ${{ secrets.PROJECT_PATH }} &&
            git pull origin master &&
            # Commandes pour redémarrer votre application (à adapter selon votre projet)
            # Par exemple: npm install && npm run build && pm2 restart app
          '
